[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
  me-no-dev/ESPAsyncWebServer@^1.2.3
  me-no-dev/ESPAsyncTCP@^1.2.2
  bblanchon/ArduinoJson@^6.21.3
  adafruit/DHT sensor library